Repository CB-Group-6-Project-1/travel-board, pull requests merged in 2020-05, with the labels that each got.

#2 proposal readme
  README.md
  assets/images/add-vacation-page.png
  assets/images/city-page.png
  assets/images/home-page.png
  assets/images/travel-board-logo.png
  assets/images/vacation-calendar-page.png
  assets/images/whiteboard.png
  assets/style.css
Labels: documentation

#4 Make MVP bullet list; Add Motivation section
  README.md
Labels: documentation

#10 Added the project structure
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: project-setup

#11 Home page
  README.md
  assets/css/style.css
  assets/images/home-page-imgs/london.jpg
  assets/images/home-page-imgs/maui.jpg
  assets/images/home-page-imgs/new-zealand.jpg
  assets/images/home-page-imgs/paris.jpg
  assets/images/home-page-imgs/rome.jpg
  assets/images/home-page-imgs/tahiti.jpg
  assets/images/readme-imgs/add-vacation-page.png
  assets/images/readme-imgs/city-page.png
  assets/images/readme-imgs/home-page.png
  assets/images/readme-imgs/travel-board-logo.png
  assets/images/readme-imgs/vacation-calendar-page.png
  assets/images/readme-imgs/whiteboard.png
  index.html
Labels: html

#36 i added the basic HTML structure of the vacation planner page
  assets/css/style.css
  index.html
Labels: html

#37 initial html for city details section
  index.html
Labels: project-setup

#38 Search destination
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: mvp

#39 added on click for popular destinations
  assets/js/script.js
  index.html
Labels: mvp

#42 Added function to load city details
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: mvp

#44 15 destination section details
  assets/js/script.js
  index.html
Labels: mvp

#45 Weather destination
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: mvp

#46 added function to get city lat and lon
  assets/js/script.js
  index.html
Labels: mvp

#54 Map destination
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: mvp

#56 Added the market for the city given the center
  assets/js/script.js
Labels: mvp

#58 changed the zoom number to 5
  assets/js/script.js
Labels: mvp
