Repository CB-Group-6-Project-1/travel-board, pull requests merged in 2020-06, with the labels that each got.

#63 62 plan vacation section update
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: mvp

#64 61 data validation
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: mvp

#66 Select start-end dates
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: mvp

#69 Fix bugs
  assets/css/style.css
  assets/images/home-page-imgs/maui.jpg
  assets/images/home-page-imgs/miami.jpg
  assets/images/home-page-imgs/new-zealand.jpg
  assets/images/home-page-imgs/sanfrancisco.jpg
  assets/images/home-page-imgs/tahiti.jpg
  assets/images/home-page-imgs/vegas.jpg
  assets/js/script.js
  index.html
Labels: mvp

#76 Save vacation plan
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: mvp

#77 Load active vacation
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: mvp

#78 Group plans
  assets/js/script.js
  index.html
Labels: mvp

#83 Added the validation to vacation plan
  assets/js/script.js
Labels: mvp

#88 35 delete trip
  assets/js/script.js
  index.html
Labels: mvp

#93 Improve ui design
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: enhancement

#99 Update README.md
  README.md
Labels: documentation

#101 Images validation when is no data
  assets/css/style.css
  assets/images/home-page-imgs/image.jpg
  assets/js/script.js
Labels: bug

#102 Add modals
  assets/js/script.js
  index.html
Labels: enhancement, modals, validation

#104 added a fresh font for the page
  assets/css/style.css
Labels: enhancement

#106 Project review
  README.md
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: enhancement

#108 Added documentation to the js files
  assets/js/city.js
  assets/js/core.js
Labels: documentation

#109 Fix images hover on small screens
  assets/css/style.css
Labels: bug

#111 User experience improve
  assets/js/city.js
  assets/js/vacation.js
  index.html
Labels: enhancement

#112 Updated demo gif in readMe
  README.md
  assets/images/readme-imgs/travel-board-demo-gif.gif
  assets/images/readme-imgs/travel-board-demo-gif2.gif
Labels: documentation

#113 User experience improve
  assets/css/style.css
  index.html
Labels: bug

#115 Add point of interest to map
  assets/css/style.css
  assets/js/city.js
  assets/js/core.js
Labels: enhancement

#116 Readme last update
  README.md
Labels: documentation

#119 Added missing Tech to the readme
  README.md
Labels: documentation
